<template>
    <div class="template-container formInput">
        <div class="form-group">
            <label>劵类型</label>
            <div class="iBox">
                <select class="form-control" v-model="discountsCur">
                    <option v-for="(item,idx) in discounts" :value="idx">{{item.name}}</option>
                </select>
            </div>
        </div>
        <div class="form-group" v-for="(item,idx) in discounts[discountsCur].inputs">
            <label>{{item.label}}</label>
            <div class="iBox" v-if="item.type=='inputText'">
                <input type="text" v-model="item.value" @input="inputFn" class="form-control"  :placeholder="item.placeholder" data-type="noEach">
            </div>
        </div>
    </div>
</template>
<script>
    import './scss/formDiscounts.scss';
    export default{
        data(){
            return{
                discounts:[
                    {
                        name:'代金卷',
                        inputs:[
                            {
                                label:'生效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'失效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'发行数量',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用城市',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用品类',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'最低消费',
                                type:'inputText',
                                placeholder:'￥',
                                value:''
                            },
                            {
                                label:'折扣',
                                type:'inputText',
                                placeholder:'￥',
                                value:''
                            },
                            {
                                label:'适用规则',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            }
                        ]
                    },
                    {
                        name:'礼品卷',
                        inputs:[
                            {
                                label:'生效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'失效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'发行数量',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用城市',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用品类',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'最低消费',
                                type:'inputText',
                                placeholder:'￥',
                                value:''
                            },
                            {
                                label:'礼品',
                                type:'inputText',
                                placeholder:'输入',
                                value:''
                            },
                            {
                                label:'适用规则',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            }
                        ]
                    },
                    {
                        name:'体验卷',
                        inputs:[
                            {
                                label:'生效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'失效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'发行数量',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用城市',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用品类',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'最低消费',
                                type:'inputText',
                                placeholder:'￥',
                                value:''
                            },
                            {
                                label:'体验',
                                type:'inputText',
                                placeholder:'输入',
                                value:''
                            },
                            {
                                label:'适用规则',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            }
                        ]
                    },
                    {
                        name:'折扣卷',
                        inputs:[
                            {
                                label:'生效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'失效时间',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'发行数量',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用城市',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用品类',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'最低消费',
                                type:'inputText',
                                placeholder:'￥',
                                value:''
                            },
                            {
                                label:'折扣',
                                type:'inputText',
                                placeholder:'',
                                value:''
                            },
                            {
                                label:'适用规则',
                                type:'inputText',
                                placeholder:'输入',
                                value:''
                            }
                        ]
                    }
                ],
                discountsCur:0
            }
        },
        methods:{
            inputFn(){
                this.$emit('upEdit','discount',this.discounts[this.discountsCur]);
            }
        },
        watch:{
            discountsCur(val,oldVal){
                this.$emit('upEdit','discount',this.discounts[val]);
            }
        }
    }
</script>
